import type { Mood } from "@/utils/themeMap";
import data from "./fragrances.json";

export type Fragrance = {
    id: string;
    name: string;
    brand: string;
    collection?: string;

    image: string;

    // The first tag sets the fragrance page theme.
    tags: Mood[];

    description: string;

    notes: {
        top: string[];
        mid: string[];
        base: string[];
    };
};

// fragrances.json is generated by `npm run import:fragrances`.
// Edit data/import/fragrances.csv instead of the JSON file.
export const fragrances = data as Fragrance[];
